# Generated by Django 5.1.2 on 2024-10-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
